---
- name: BACK | Checks if Composer is already installed
  command: "{{ composer_path }}"
  ignore_errors: true
  register: composer_installed

- name: BACK | Install Composer if its not already installed
  block:

    - name: BACK | Download Composer Installation Script (if not already installed)
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: BACK | Run Composer Installer (if not already installed)
      command:
        cmd: /usr/bin/php /tmp/composer-setup.php
        creates: composer.phar

    - name: BACK | Copy Composer Executable to /usr/local/bin
      become: true
      copy:
        src: composer.phar
        dest: /usr/local/bin/composer
        remote_src: yes
        mode: '0755'

    - name: BACK | Remove phar
      file:
        path: composer.phar
        state: absent

    - name: BACK | Remove Install Script
      file:
        path: /tmp/composer-setup.php
        state: absent

  when: composer_installed is failed